version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .prod.env
    ports:
      - 127.0.0.1:8080:8080
  
  postgres:
    image: postgres:latest
    env_file:
      - .prod.env
    environment:
      PGDATA: /var/lib/postgresql/data/db
    volumes:
      - pg-db:/var/lib/postgresql/data

volumes:
  hcc_db: